# Generated by Django 4.0.6 on 2022-08-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='addr',
            new_name='address',
        ),
    ]
