# Generated by Django 4.0.6 on 2022-08-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('phone', models.TextField(max_length=30)),
                ('pw', models.TextField(max_length=30)),
                ('addr', models.TextField()),
            ],
        ),
    ]
