# Generated by Django 4.0.6 on 2022-08-04 03:24

# Generated by Django 4.0.6 on 2022-08-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sido', models.TextField()),
                ('sigun', models.TextField()),
                ('addr', models.TextField()),
                ('phone', models.TextField()),
                ('url', models.URLField(max_length=50)),
                ('yy', models.TextField()),
                ('xx', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField(unique=True)),
                ('pw', models.TextField()),
                ('gender', models.CharField(max_length=200)),
                ('addr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('email', models.TextField(unique=True)),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('rdate', models.DateTimeField()),
                ('views', models.TextField()),
            ],
        ),
    ]
