# Generated by Django 4.0.6 on 2022-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('hosname', models.TextField()),
                ('symptom', models.TextField()),
                ('content', models.TextField()),
                ('bdate', models.DateTimeField()),
                ('btime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('event_name', models.TextField()),
                ('rdate', models.DateTimeField()),
                ('img_address', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField(unique=True)),
                ('pw', models.TextField()),
                ('gender', models.CharField(max_length=200)),
                ('addr', models.TextField()),
                ('phoneNum', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Myevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('title', models.TextField()),
                ('hosname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('rdate', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('hosname', models.TextField()),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
