# Generated by Django 4.0.6 on 2022-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField(unique=True)),
                ('pw', models.TextField()),
                ('gender', models.CharField(max_length=200)),
                ('addr', models.TextField()),
                ('phoneNum', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('email', models.TextField(unique=True)),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('rdate', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('hosname', models.TextField()),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
