# Generated by Django 4.0.6 on 2022-08-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team2app', '0002_member1_review1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
