# Generated by Django 4.0.6 on 2022-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2app', '0002_member1_review1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review1',
            name='email',
            field=models.TextField(),
        ),
    ]
