# Generated by Django 4.0.6 on 2022-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2app', '0003_alter_review1_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('title', models.TextField()),
                ('hosname', models.TextField()),
            ],
        ),
    ]
