from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/search_ok/', views.search_ok, name='search_ok'),
    path('review/', views.review, name='review'),  
    path('map/', views.map, name='map'),
    path('login/', views.login, name='login'),
    path('login/login_ok/', views.login_ok, name='login_ok'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('healthinfo/', views.healthinfo, name='healthinfo'),
    path('event/', views.event, name='event'),
    path('econtent/<int:id>', views.econtent, name='econtent'),
    path('econtent/dibs/<int:id>', views.dibs, name='dibs'),
    path('mypage/dibsdelete/<str:title>', views.dibsdelete, name='dibsdelete'),
    path('mypage/', views.mypage, name='mypage'),
    path('rwrite/', views.rwrite, name='rwrite'),
    path('rwrite/rwrite_ok/', views.rwrite_ok, name='rwrite_ok'),
    path('rcontent/<int:id>', views.rcontent, name='rcontent'),
    path('rdelete/<int:id>', views.rdelete, name='rdelete'),
    path('rupdate/<int:id>', views.rupdate, name='rupdate'),
    path('rupdate/rupdate_ok/<int:id>', views.rupdate_ok, name='rupdate_ok'),
    path('book/<int:num>', views.book, name='book'),
    path('book/<int:num>/book_ok/', views.book_ok, name='book_ok'),
    path('book/book_ok/', views.book_ok, name='book_ok'), 
    path('mypage/update_ok/', views.update_ok, name='update_ok'),  
]